package restricted;

import haxe.rtti.Meta;

//Static helper functions that aren't exposed to users with scripting.
class RestrictedUtils
{

	//Force a call to a function generated by a macro etc. that did not exist at compile time.
	public static inline function callStaticGeneratedMethod(from:Class<Dynamic>, func:String, ?args:Array<Dynamic>):Dynamic{
		return Reflect.callMethod(null, Reflect.getProperty(from, func), args);
	}

	public static inline function hasMetadata(cls:Class<Dynamic>, variable:String, meta:String):Bool{
		var classFields = Meta.getStatics(cls);
		if (!Reflect.hasField(classFields, variable)){
			return false;
		}

		return Reflect.hasField(Reflect.field(classFields, variable), meta);
	}

	public static function createDirectoryIfNonexistent(dir:String):Void{
		if(!directoryExists(dir)){
		#if sys
		sys.FileSystem.createDirectory(dir);
		#else
		throw 'Directory creation is not supported on this platform.';
		#end
		}
	}

	public static function directoryExists(path:String):Bool{
		#if sys
		try{
			return sys.FileSystem.isDirectory(path);
		}
		catch(e:Dynamic){
			return false;
		}
		#else
		throw 'Filesystem check is not supported on this platform.';
		#end
	}
}