package restricted;

//Static helper functions that aren't exposed to users with scripting.
class RestrictedUtils
{

	//Force a call to a function generated by a macro etc. that did not exist at compile time.
	public static inline function callStaticGeneratedMethod(from:Class<Dynamic>, func:String, ?args:Array<Dynamic>):Dynamic{
		return Reflect.callMethod(null, Reflect.getProperty(from, func), args);
	}

}